version: "3.6"
services:

  db:
    image: postgres:12.5
    container_name: postgres_new_bridge
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: neo
      POSTGRES_DB: retro_board_db
      restart: always

volumes:
  db_data:
